apiVersion: 1

datasources:
  - name: Infinity CSV INMET
    type: yesoreyeram-infinity-datasource
    uid: ef5ezkch2esxse   # vamos ajustar o UID abaixo
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      datasource_mode: 'basic'
